//
//  Constants.swift
//  saga
//
//  Created by Christian McCartney on 10/22/21.
//

import CoreGraphics

let MIN_ZOOM_SCALE = 0.25
let MAX_ZOOM_SCALE = 1.0

let TEXT_SPRITE_SHEET_WIDTH: CGFloat = 216
let TEXT_SPRITE_SHEET_HEIGHT: CGFloat = 42
let TEXT_SPRITE_SHEET_WRAP = 36

let TEXT_SPRITE_WIDTH: CGFloat = 6
let TEXT_SPRITE_HEIGHT: CGFloat = 7
let TEXT_SPRITE_SIZE: CGSize = CGSize(width: TEXT_SPRITE_WIDTH, height: TEXT_SPRITE_HEIGHT)

let STANDARD_TEXTURE_WIDTH: Int = 16
let STANDARD_TEXTURE_HEIGHT: Int = 16

let STANDARD_WEAPON_WIDTH: Int = 100
let STANDARD_WEAPON_HEIGHT: Int = 100

let STANDARD_MAP_SIZE: Int = 48

let STANDARD_BUTTON_SIZE: CGFloat = 48
let STANDARD_PANEL_SIZE: CGFloat = 64
let EQUIPMENT_SLOT_SIZE: CGFloat = 100
